[inputs.local_rules]
type = "local"
path = "./.ai"

[inputs.my_ai_presets_example1]
type = "git"
repository = "https://github.com/sushichan044/ai-presets.git"
directory = "example1"

[outputs.cursor]
target = "cursor"
enabled = true

[outputs.github-copilot]
target = "github-copilot"
enabled = true

[outputs.windsurf]
target = "windsurf"
enabled = true
