[tools]
golangci-lint = "latest"
gotestsum = "latest"

[env]
GO111MODULE = "on"

[tasks.lint]
description = "Run golangci-lint"
run = "golangci-lint run ./..."

[tasks.lint-fix]
description = "Fix golangci-lint issues automatically"
run = "golangci-lint run --fix ./..."

[tasks.fmt]
description = "Format code"
run = "golangci-lint fmt"

[tasks.test]
description = "Run tests"
run = "gotestsum"

[tasks.build-snapshot]
description = "Build the application with version info"
run = "goreleaser release --clean --snapshot"

[tasks.dev]
description = "Run the application in development mode"
run = "go run main.go"

[tasks.clean]
description = "Remove generated files"
run = """
rm -rf bin/
go clean
"""
